<?php
if (!defined('ABSPATH')) { exit; }

/**
 * ACF Pro: About Us Page – Hero, Mission, Legacy, CTA, Values
 */
function mlzs_acf_about_us_field_group() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }
    acf_add_local_field_group(array(
        'key'                   => 'group_mlzs_about_us',
        'title'                 => __('About Us Page Sections', 'mlzs'),
        'fields'                => array(
            array('key' => 'field_about_tab_hero', 'label' => __('Hero Section', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_about_hero_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'about_hero_badge',
                'type' => 'text',
                'default_value' => 'Our Story & Legacy',
            ),
            array(
                'key' => 'field_about_hero_headline',
                'label' => __('Headline (before highlight)', 'mlzs'),
                'name' => 'about_hero_headline',
                'type' => 'text',
                'default_value' => 'About',
            ),
            array(
                'key' => 'field_about_hero_highlight',
                'label' => __('Headline (highlighted part)', 'mlzs'),
                'name' => 'about_hero_highlight',
                'type' => 'text',
                'default_value' => 'Mount Litera',
            ),
            array(
                'key' => 'field_about_hero_headline_suffix',
                'label' => __('Headline (after highlight)', 'mlzs'),
                'name' => 'about_hero_headline_suffix',
                'type' => 'text',
                'default_value' => 'Zee School',
            ),
            array(
                'key' => 'field_about_hero_subheadline',
                'label' => __('Subheadline', 'mlzs'),
                'name' => 'about_hero_subheadline',
                'type' => 'textarea',
                'rows' => 3,
                'default_value' => 'Preparing leaders of the 21st century through innovative education that blends tradition with modernity, values with technology.',
            ),
            array(
                'key' => 'field_about_hero_cta_primary',
                'label' => __('Primary Button (Our Mission)', 'mlzs'),
                'name' => 'about_hero_cta_primary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_hero_cta_primary_icon',
                'label' => __('Primary Button Icon', 'mlzs'),
                'name' => 'about_hero_cta_primary_icon',
                'type' => 'text',
                'default_value' => 'arrow-down',
            ),
            array(
                'key' => 'field_about_hero_cta_secondary',
                'label' => __('Secondary Button (Our Legacy)', 'mlzs'),
                'name' => 'about_hero_cta_secondary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_hero_cta_secondary_icon',
                'label' => __('Secondary Button Icon', 'mlzs'),
                'name' => 'about_hero_cta_secondary_icon',
                'type' => 'text',
                'default_value' => 'history',
            ),
            array(
                'key' => 'field_about_hero_bg_image',
                'label' => __('Hero Background Image', 'mlzs'),
                'name' => 'about_hero_bg_image',
                'type' => 'image',
                'return_format' => 'url',
                'required' => 0,
            ),
            array('key' => 'field_about_tab_mission', 'label' => __('Mission & Overview', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_about_mission_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'about_mission_badge',
                'type' => 'text',
                'default_value' => 'Our Endeavour',
            ),
            array(
                'key' => 'field_about_mission_heading',
                'label' => __('Section Heading', 'mlzs'),
                'name' => 'about_mission_heading',
                'type' => 'text',
                'default_value' => 'Mount Litera Zee School',
            ),
            array(
                'key' => 'field_about_mission_paragraphs',
                'label' => __('Description Paragraphs', 'mlzs'),
                'name' => 'about_mission_paragraphs',
                'type' => 'textarea',
                'rows' => 6,
                'default_value' => "Mount Litera Zee School is an endeavor by the Essel Group to prepare leaders of the 21st century through its Education arm, Zee Learn Limited.\n\nWith more than 65 schools in 55 cities, Mount Litera Zee School is India's fastest growing network of K12 schools.\n\nZee Learn Limited has its preschool network Kidzee with more than 1350 preschools in India and is Asia's largest network of preschools.",
            ),
            array(
                'key' => 'field_about_mission_stats',
                'label' => __('Stats (2 boxes)', 'mlzs'),
                'name' => 'about_mission_stats',
                'type' => 'repeater',
                'min' => 2,
                'max' => 2,
                'layout' => 'table',
                'button_label' => __('Add Stat', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_about_mission_stat_number', 'label' => __('Number', 'mlzs'), 'name' => 'number', 'type' => 'text', 'default_value' => '65+'),
                    array('key' => 'field_about_mission_stat_label', 'label' => __('Label', 'mlzs'), 'name' => 'label', 'type' => 'text', 'default_value' => 'Schools Across India'),
                ),
            ),
            array(
                'key' => 'field_about_mission_image',
                'label' => __('Right Side Image', 'mlzs'),
                'name' => 'about_mission_image',
                'type' => 'image',
                'return_format' => 'url',
            ),
            array(
                'key' => 'field_about_mission_image_title',
                'label' => __('Image Overlay Title', 'mlzs'),
                'name' => 'about_mission_image_title',
                'type' => 'text',
                'default_value' => 'Innovative Learning Environment',
            ),
            array(
                'key' => 'field_about_mission_image_caption',
                'label' => __('Image Overlay Caption', 'mlzs'),
                'name' => 'about_mission_image_caption',
                'type' => 'text',
                'default_value' => 'State-of-the-art infrastructure for holistic development',
            ),
            array('key' => 'field_about_tab_legacy', 'label' => __('Legacy Section', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_about_legacy_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'about_legacy_badge',
                'type' => 'text',
                'default_value' => 'Our Legacy',
            ),
            array(
                'key' => 'field_about_legacy_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name' => 'about_legacy_badge_icon',
                'type' => 'text',
                'default_value' => 'sparkles',
            ),
            array(
                'key' => 'field_about_legacy_heading',
                'label' => __('Heading (before highlight)', 'mlzs'),
                'name' => 'about_legacy_heading',
                'type' => 'text',
                'default_value' => 'The',
            ),
            array(
                'key' => 'field_about_legacy_highlight',
                'label' => __('Heading (highlighted)', 'mlzs'),
                'name' => 'about_legacy_highlight',
                'type' => 'text',
                'default_value' => 'Legacy',
            ),
            array(
                'key' => 'field_about_legacy_heading_suffix',
                'label' => __('Heading (after highlight)', 'mlzs'),
                'name' => 'about_legacy_heading_suffix',
                'type' => 'text',
                'default_value' => 'of Excellence',
            ),
            array(
                'key' => 'field_about_legacy_intro',
                'label' => __('Intro Paragraph', 'mlzs'),
                'name' => 'about_legacy_intro',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => "Pioneering educational innovation since 1994, shaping minds and building futures",
            ),
            array(
                'key' => 'field_about_legacy_image',
                'label' => __('Legacy Image', 'mlzs'),
                'name' => 'about_legacy_image',
                'type' => 'image',
                'return_format' => 'url',
            ),
            array(
                'key' => 'field_about_legacy_year',
                'label' => __('Year Card Number', 'mlzs'),
                'name' => 'about_legacy_year',
                'type' => 'text',
                'default_value' => '1994',
            ),
            array(
                'key' => 'field_about_legacy_year_label',
                'label' => __('Year Card Label', 'mlzs'),
                'name' => 'about_legacy_year_label',
                'type' => 'text',
                'default_value' => 'Year of Foundation',
            ),
            array(
                'key' => 'field_about_legacy_year_caption',
                'label' => __('Year Card Caption', 'mlzs'),
                'name' => 'about_legacy_year_caption',
                'type' => 'text',
                'default_value' => 'Innovation leader in Indian education',
            ),
            array(
                'key' => 'field_about_legacy_paragraphs',
                'label' => __('Body Paragraphs', 'mlzs'),
                'name' => 'about_legacy_paragraphs',
                'type' => 'textarea',
                'rows' => 5,
                'default_value' => "Mount Litera Zee School is an endeavour by the Essel Group led by Shri Subhash Chandra to prepare leaders of the 21st century through its education arm, Zee Learn Limited.\n\nZee Learn Limited is an innovation leader in Indian education since 1994. We introduced various firsts in the country ranging from Zeed, Kidzee preschools, Mount Litera Zee Schools, Mount Litera School International, BrainCalfeSchool Programs and Zee Institutes of Media Art and Creative Art.",
            ),
            array(
                'key' => 'field_about_legacy_vision_title',
                'label' => __('Vision Box Title', 'mlzs'),
                'name' => 'about_legacy_vision_title',
                'type' => 'text',
                'default_value' => 'Our Vision',
            ),
            array(
                'key' => 'field_about_legacy_vision_text',
                'label' => __('Vision Box Text', 'mlzs'),
                'name' => 'about_legacy_vision_text',
                'type' => 'textarea',
                'rows' => 3,
                'default_value' => 'The aim of Mount Litera Zee Schools is to establish social spaces in the country for providing quality educational experiences to improve human capital and create quality manpower for a knowledge society.',
            ),
            array(
                'key' => 'field_about_legacy_stats',
                'label' => __('Legacy Stats (3 boxes)', 'mlzs'),
                'name' => 'about_legacy_stats',
                'type' => 'repeater',
                'min' => 3,
                'max' => 3,
                'layout' => 'table',
                'button_label' => __('Add Stat', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_about_legacy_stat_number', 'label' => __('Number', 'mlzs'), 'name' => 'number', 'type' => 'text'),
                    array('key' => 'field_about_legacy_stat_label', 'label' => __('Label', 'mlzs'), 'name' => 'label', 'type' => 'text'),
                ),
            ),
            array('key' => 'field_about_tab_cta', 'label' => __('CTA Section', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_about_cta_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'about_cta_badge',
                'type' => 'text',
                'default_value' => 'Join Our Community',
            ),
            array(
                'key' => 'field_about_cta_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name' => 'about_cta_badge_icon',
                'type' => 'text',
                'default_value' => 'star',
            ),
            array(
                'key' => 'field_about_cta_heading',
                'label' => __('Heading (before highlight)', 'mlzs'),
                'name' => 'about_cta_heading',
                'type' => 'text',
                'default_value' => 'Be Part of the Mount Litera',
            ),
            array(
                'key' => 'field_about_cta_highlight',
                'label' => __('Heading (highlighted)', 'mlzs'),
                'name' => 'about_cta_highlight',
                'type' => 'text',
                'default_value' => 'Legacy',
            ),
            array(
                'key' => 'field_about_cta_description',
                'label' => __('Description', 'mlzs'),
                'name' => 'about_cta_description',
                'type' => 'textarea',
                'rows' => 3,
                'default_value' => "Join India's fastest growing network of K12 schools and give your child the gift of world-class education combined with strong values and innovative learning.",
            ),
            array(
                'key' => 'field_about_cta_primary',
                'label' => __('Primary Button', 'mlzs'),
                'name' => 'about_cta_primary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_cta_primary_icon',
                'label' => __('Primary Button Icon', 'mlzs'),
                'name' => 'about_cta_primary_icon',
                'type' => 'text',
                'default_value' => 'arrow-right',
            ),
            array(
                'key' => 'field_about_cta_secondary',
                'label' => __('Secondary Button', 'mlzs'),
                'name' => 'about_cta_secondary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_cta_secondary_icon',
                'label' => __('Secondary Button Icon', 'mlzs'),
                'name' => 'about_cta_secondary_icon',
                'type' => 'text',
                'default_value' => 'phone',
            ),
            array('key' => 'field_about_tab_values', 'label' => __('Values & Philosophy', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_about_values_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'about_values_badge',
                'type' => 'text',
                'default_value' => 'Our Values',
            ),
            array(
                'key' => 'field_about_values_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name' => 'about_values_badge_icon',
                'type' => 'text',
                'default_value' => 'heart',
            ),
            array(
                'key' => 'field_about_values_heading',
                'label' => __('Heading (before highlight)', 'mlzs'),
                'name' => 'about_values_heading',
                'type' => 'text',
                'default_value' => 'Educational',
            ),
            array(
                'key' => 'field_about_values_highlight',
                'label' => __('Heading (highlighted)', 'mlzs'),
                'name' => 'about_values_highlight',
                'type' => 'text',
                'default_value' => 'Philosophy',
            ),
            array(
                'key' => 'field_about_values_intro',
                'label' => __('Intro Paragraph', 'mlzs'),
                'name' => 'about_values_intro',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'We believe in creating social spaces for quality education that builds human capital for a knowledge society',
            ),
            array(
                'key' => 'field_about_values_cards',
                'label' => __('Value Cards (3)', 'mlzs'),
                'name' => 'about_values_cards',
                'type' => 'repeater',
                'min' => 3,
                'max' => 3,
                'layout' => 'block',
                'button_label' => __('Add Card', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_about_values_card_icon', 'label' => __('Lucide Icon', 'mlzs'), 'name' => 'icon', 'type' => 'text', 'default_value' => 'users'),
                    array('key' => 'field_about_values_card_title', 'label' => __('Title', 'mlzs'), 'name' => 'title', 'type' => 'text'),
                    array('key' => 'field_about_values_card_description', 'label' => __('Description', 'mlzs'), 'name' => 'description', 'type' => 'textarea', 'rows' => 3),
                    array(
                        'key' => 'field_about_values_card_style',
                        'label' => __('Card Style', 'mlzs'),
                        'name' => 'style',
                        'type' => 'select',
                        'choices' => array('primary' => 'Primary (purple)', 'accent' => 'Accent (amber)', 'primary-light' => 'Primary Light'),
                        'default_value' => 'primary',
                    ),
                ),
            ),
            array(
                'key' => 'field_about_commitment_heading',
                'label' => __('Commitment Box Heading', 'mlzs'),
                'name' => 'about_commitment_heading',
                'type' => 'text',
                'default_value' => 'Our Commitment to Excellence',
            ),
            array(
                'key' => 'field_about_commitment_text',
                'label' => __('Commitment Box Text', 'mlzs'),
                'name' => 'about_commitment_text',
                'type' => 'textarea',
                'rows' => 4,
                'default_value' => 'Mount Litera Zee School synthesizes human values with the highest quality of teaching-learning using modern technology-driven tools. We prepare well-rounded personalities who can lead effectively in our contemporary society.',
            ),
            array(
                'key' => 'field_about_commitment_cta_primary',
                'label' => __('Commitment Primary Button', 'mlzs'),
                'name' => 'about_commitment_cta_primary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_commitment_cta_primary_icon',
                'label' => __('Commitment Primary Icon', 'mlzs'),
                'name' => 'about_commitment_cta_primary_icon',
                'type' => 'text',
                'default_value' => 'arrow-right',
            ),
            array(
                'key' => 'field_about_commitment_cta_secondary',
                'label' => __('Commitment Secondary Button', 'mlzs'),
                'name' => 'about_commitment_cta_secondary',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_about_commitment_cta_secondary_icon',
                'label' => __('Commitment Secondary Icon', 'mlzs'),
                'name' => 'about_commitment_cta_secondary_icon',
                'type' => 'text',
                'default_value' => 'download',
            ),
            array(
                'key' => 'field_about_commitment_stats',
                'label' => __('Commitment Stats (4 boxes)', 'mlzs'),
                'name' => 'about_commitment_stats',
                'type' => 'repeater',
                'min' => 4,
                'max' => 4,
                'layout' => 'table',
                'button_label' => __('Add Stat', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_about_commitment_stat_number', 'label' => __('Number', 'mlzs'), 'name' => 'number', 'type' => 'text'),
                    array('key' => 'field_about_commitment_stat_label', 'label' => __('Label', 'mlzs'), 'name' => 'label', 'type' => 'text'),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'about-us.php',
                ),
            ),
        ),
    ));
}
add_action('acf/init', 'mlzs_acf_about_us_field_group');
