<?php
if (!defined('ABSPATH')) { exit; }

/**
 * ACF Pro: Admission Process Page – Hero, Process Steps, Entry Criteria, Documents, Form Section
 */
function mlzs_acf_admission_process_field_group() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }
    acf_add_local_field_group(array(
        'key'                   => 'group_mlzs_admission_process',
        'title'                 => __('Admission Process Page Sections', 'mlzs'),
        'fields'                => array(
            array('key' => 'field_adm_tab_hero', 'label' => __('Hero Section', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_adm_hero_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name' => 'admission_hero_badge',
                'type' => 'text',
                'default_value' => 'Join Our Community',
            ),
            array(
                'key' => 'field_adm_hero_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name' => 'admission_hero_badge_icon',
                'type' => 'text',
                'default_value' => 'user-plus',
            ),
            array(
                'key' => 'field_adm_hero_headline',
                'label' => __('Headline (before highlight)', 'mlzs'),
                'name' => 'admission_hero_headline',
                'type' => 'text',
                'default_value' => 'Admission',
            ),
            array(
                'key' => 'field_adm_hero_highlight',
                'label' => __('Headline (highlighted)', 'mlzs'),
                'name' => 'admission_hero_highlight',
                'type' => 'text',
                'default_value' => 'Process',
            ),
            array(
                'key' => 'field_adm_hero_subheadline',
                'label' => __('Subheadline', 'mlzs'),
                'name' => 'admission_hero_subheadline',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'A seamless and transparent admission process to welcome your child into our learning community',
            ),
            array('key' => 'field_adm_tab_process', 'label' => __('Admission Process Steps', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_adm_process_heading',
                'label' => __('Card Title', 'mlzs'),
                'name' => 'admission_process_heading',
                'type' => 'text',
                'default_value' => 'Admission Process',
            ),
            array(
                'key' => 'field_adm_process_icon',
                'label' => __('Card Icon', 'mlzs'),
                'name' => 'admission_process_icon',
                'type' => 'text',
                'default_value' => 'clipboard-list',
            ),
            array(
                'key' => 'field_adm_process_steps',
                'label' => __('Process Steps', 'mlzs'),
                'name' => 'admission_process_steps',
                'type' => 'repeater',
                'min' => 1,
                'layout' => 'block',
                'button_label' => __('Add Step', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_adm_process_step_text',
                        'label' => __('Step Text', 'mlzs'),
                        'name' => 'step_text',
                        'type' => 'textarea',
                        'rows' => 2,
                    ),
                ),
            ),
            array(
                'key' => 'field_adm_process_cta',
                'label' => __('CTA Button (e.g. Start Admission Process)', 'mlzs'),
                'name' => 'admission_process_cta',
                'type' => 'link',
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_adm_process_cta_icon',
                'label' => __('CTA Icon', 'mlzs'),
                'name' => 'admission_process_cta_icon',
                'type' => 'text',
                'default_value' => 'arrow-down',
            ),
            array(
                'key' => 'field_adm_process_image',
                'label' => __('Right Side Image', 'mlzs'),
                'name' => 'admission_process_image',
                'type' => 'image',
                'return_format' => 'url',
            ),
            array(
                'key' => 'field_adm_process_image_caption',
                'label' => __('Image Overlay Caption', 'mlzs'),
                'name' => 'admission_process_image_caption',
                'type' => 'text',
                'default_value' => 'Seamless Admission Journey',
            ),
            array('key' => 'field_adm_tab_entry', 'label' => __('Entry Criteria', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_adm_entry_heading',
                'label' => __('Section Heading', 'mlzs'),
                'name' => 'admission_entry_heading',
                'type' => 'text',
                'default_value' => 'Entry Criteria for Admission',
            ),
            array(
                'key' => 'field_adm_entry_icon',
                'label' => __('Section Icon', 'mlzs'),
                'name' => 'admission_entry_icon',
                'type' => 'text',
                'default_value' => 'target',
            ),
            array(
                'key' => 'field_adm_entry_intro',
                'label' => __('Intro Paragraph', 'mlzs'),
                'name' => 'admission_entry_intro',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'Admissions are granted to students on the basis of the following assessments:',
            ),
            array(
                'key' => 'field_adm_entry_criteria',
                'label' => __('Criteria Items', 'mlzs'),
                'name' => 'admission_entry_criteria',
                'type' => 'repeater',
                'min' => 1,
                'layout' => 'block',
                'button_label' => __('Add Item', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_adm_entry_label', 'label' => __('Label (bold)', 'mlzs'), 'name' => 'label', 'type' => 'text', 'placeholder' => 'e.g. Grade 1:'),
                    array('key' => 'field_adm_entry_description', 'label' => __('Description', 'mlzs'), 'name' => 'description', 'type' => 'text', 'placeholder' => 'e.g. age 5+ as on April 1'),
                ),
            ),
            array(
                'key' => 'field_adm_entry_image',
                'label' => __('Left Side Image', 'mlzs'),
                'name' => 'admission_entry_image',
                'type' => 'image',
                'return_format' => 'url',
            ),
            array(
                'key' => 'field_adm_entry_image_caption',
                'label' => __('Image Overlay Caption', 'mlzs'),
                'name' => 'admission_entry_image_caption',
                'type' => 'text',
                'default_value' => 'Clear Entry Guidelines',
            ),
            array('key' => 'field_adm_tab_docs', 'label' => __('Documents Required', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_adm_docs_heading',
                'label' => __('Section Heading', 'mlzs'),
                'name' => 'admission_docs_heading',
                'type' => 'text',
                'default_value' => 'Documents Required',
            ),
            array(
                'key' => 'field_adm_docs_icon',
                'label' => __('Section Icon', 'mlzs'),
                'name' => 'admission_docs_icon',
                'type' => 'text',
                'default_value' => 'folder-open',
            ),
            array(
                'key' => 'field_adm_docs_intro',
                'label' => __('Intro Paragraph', 'mlzs'),
                'name' => 'admission_docs_intro',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'Documents to be submitted at the time of admission:',
            ),
            array(
                'key' => 'field_adm_docs_items',
                'label' => __('Document Items', 'mlzs'),
                'name' => 'admission_docs_items',
                'type' => 'repeater',
                'min' => 1,
                'layout' => 'block',
                'button_label' => __('Add Document', 'mlzs'),
                'sub_fields' => array(
                    array('key' => 'field_adm_docs_item_icon', 'label' => __('Lucide Icon', 'mlzs'), 'name' => 'icon', 'type' => 'text', 'default_value' => 'file-text'),
                    array('key' => 'field_adm_docs_item_title', 'label' => __('Title', 'mlzs'), 'name' => 'title', 'type' => 'text'),
                    array('key' => 'field_adm_docs_item_description', 'label' => __('Description', 'mlzs'), 'name' => 'description', 'type' => 'text'),
                ),
            ),
            array(
                'key' => 'field_adm_docs_image',
                'label' => __('Right Side Image', 'mlzs'),
                'name' => 'admission_docs_image',
                'type' => 'image',
                'return_format' => 'url',
            ),
            array(
                'key' => 'field_adm_docs_image_caption',
                'label' => __('Image Overlay Caption', 'mlzs'),
                'name' => 'admission_docs_image_caption',
                'type' => 'text',
                'default_value' => 'Required Documentation',
            ),
            array('key' => 'field_adm_tab_form', 'label' => __('Registration Form Section', 'mlzs'), 'name' => '', 'type' => 'tab'),
            array(
                'key' => 'field_adm_form_badge',
                'label' => __('Form Section Badge', 'mlzs'),
                'name' => 'admission_form_badge',
                'type' => 'text',
                'default_value' => 'Online Registration',
            ),
            array(
                'key' => 'field_adm_form_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name' => 'admission_form_badge_icon',
                'type' => 'text',
                'default_value' => 'edit-3',
            ),
            array(
                'key' => 'field_adm_form_heading',
                'label' => __('Form Heading', 'mlzs'),
                'name' => 'admission_form_heading',
                'type' => 'text',
                'default_value' => 'Registration Form',
            ),
            array(
                'key' => 'field_adm_form_description',
                'label' => __('Form Description', 'mlzs'),
                'name' => 'admission_form_description',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => "Fill in the details below to begin your child's admission journey with us",
            ),
            array(
                'key' => 'field_adm_form_submit_text',
                'label' => __('Submit Button Text', 'mlzs'),
                'name' => 'admission_form_submit_text',
                'type' => 'text',
                'default_value' => 'Submit Registration Form',
            ),
            array(
                'key' => 'field_adm_form_terms_text',
                'label' => __('Terms Text (below button)', 'mlzs'),
                'name' => 'admission_form_terms_text',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'By submitting this form, you agree to our terms and conditions.',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'admission-process.php',
                ),
            ),
        ),
    ));
}
add_action('acf/init', 'mlzs_acf_admission_process_field_group');
