<?php
if (!defined('ABSPATH')) { exit; }

/**
 * ACF Pro: Home Page Sections – Hero, Welcome, etc. (section-wise tabs when editing Home page)
 */
function mlzs_acf_hero_field_group() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }
    acf_add_local_field_group(array(
        'key'                   => 'group_mlzs_hero',
        'title'                 => 'Home Page Sections',
        'fields'                => array(
            array(
                'key'   => 'field_tab_hero',
                'label' => __('Hero Section', 'mlzs'),
                'name'  => '',
                'type'  => 'tab',
            ),
            array(
                'key'   => 'field_hero_slides',
                'label' => __('Hero Slides', 'mlzs'),
                'name'  => 'hero_slides',
                'type'  => 'repeater',
                'instructions' => __('Add image or video slides. Videos play for full duration; image slides use delay from CMS.', 'mlzs'),
                'min'   => 1,
                'layout' => 'block',
                'button_label' => __('Add Slide', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key'   => 'field_hero_slide_type',
                        'label' => __('Slide Type', 'mlzs'),
                        'name'  => 'slide_type',
                        'type'  => 'select',
                        'choices' => array(
                            'image' => __('Image', 'mlzs'),
                            'video' => __('Video', 'mlzs'),
                        ),
                        'default_value' => 'image',
                        'ui' => 1,
                    ),
                    array(
                        'key'   => 'field_hero_slide_image',
                        'label' => __('Slide Image', 'mlzs'),
                        'name'  => 'slide_image',
                        'type'  => 'image',
                        'required' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_video',
                        'label' => __('Slide Video (local upload)', 'mlzs'),
                        'name'  => 'slide_video',
                        'type'  => 'file',
                        'required' => 0,
                        'return_format' => 'url',
                        'mime_types' => 'mp4,webm,ogg',
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'video',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_image_delay',
                        'label' => __('Image Slide Delay (seconds)', 'mlzs'),
                        'name'  => 'slide_delay_seconds',
                        'type'  => 'number',
                        'default_value' => 5,
                        'min' => 1,
                        'max' => 30,
                        'step' => 1,
                        'instructions' => __('Used only for image slides.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_show_content',
                        'label' => __('Show Hero Content On This Image Slide', 'mlzs'),
                        'name'  => 'show_content',
                        'type'  => 'true_false',
                        'message' => __('Show badge/heading/buttons/stats overlay on this slide', 'mlzs'),
                        'ui' => 1,
                        'default_value' => 0,
                        'instructions' => __('Enable this on one image slide if you want the current hero text only once.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_badge_text',
                        'label' => __('Slide Badge Text (optional)', 'mlzs'),
                        'name'  => 'slide_badge_text',
                        'type'  => 'text',
                        'instructions' => __('Leave empty to use default hero badge.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_headline_line1',
                        'label' => __('Slide Headline (First Line, optional)', 'mlzs'),
                        'name'  => 'slide_headline_line1',
                        'type'  => 'text',
                        'instructions' => __('Leave empty to use default hero headline first line.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_headline_highlight',
                        'label' => __('Slide Headline Highlight (optional)', 'mlzs'),
                        'name'  => 'slide_headline_highlight',
                        'type'  => 'text',
                        'instructions' => __('Leave empty to use default hero highlight text.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_subheadline',
                        'label' => __('Slide Subheadline (optional)', 'mlzs'),
                        'name'  => 'slide_subheadline',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'instructions' => __('Leave empty to use default hero subheadline.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_cta_primary',
                        'label' => __('Slide Primary Button Link (optional)', 'mlzs'),
                        'name'  => 'slide_cta_primary',
                        'type'  => 'link',
                        'return_format' => 'array',
                        'instructions' => __('Leave empty to use default primary button.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_cta_primary_icon',
                        'label' => __('Slide Primary Button Icon (optional)', 'mlzs'),
                        'name'  => 'slide_cta_primary_icon',
                        'type'  => 'text',
                        'instructions' => __('Leave empty to use default primary icon.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_cta_secondary',
                        'label' => __('Slide Secondary Button Link (optional)', 'mlzs'),
                        'name'  => 'slide_cta_secondary',
                        'type'  => 'link',
                        'return_format' => 'array',
                        'instructions' => __('Leave empty to use default secondary button.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_hero_slide_cta_secondary_icon',
                        'label' => __('Slide Secondary Button Icon (optional)', 'mlzs'),
                        'name'  => 'slide_cta_secondary_icon',
                        'type'  => 'text',
                        'instructions' => __('Leave empty to use default secondary icon.', 'mlzs'),
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_hero_slide_type',
                                    'operator' => '==',
                                    'value' => 'image',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key'   => 'field_hero_badge_text',
                'label' => __('Badge Text', 'mlzs'),
                'name'  => 'hero_badge_text',
                'type'  => 'text',
                'default_value' => 'Admissions Open for 2025-26',
            ),
            array(
                'key'   => 'field_hero_headline_line1',
                'label' => __('Headline (First Line)', 'mlzs'),
                'name'  => 'hero_headline_line1',
                'type'  => 'text',
                'default_value' => 'Fun. Study. Research.',
            ),
            array(
                'key'   => 'field_hero_headline_highlight',
                'label' => __('Headline (Highlighted Part)', 'mlzs'),
                'name'  => 'hero_headline_highlight',
                'type'  => 'text',
                'default_value' => 'Innovate. Play',
            ),
            array(
                'key'   => 'field_hero_subheadline',
                'label' => __('Subheadline', 'mlzs'),
                'name'  => 'hero_subheadline',
                'type'  => 'textarea',
                'default_value' => 'A Great School For A Great Future Of Your Child. Mount Litera Zee School will provide a complete and unique educational experience for the child, preparing the child for a successful life in the contemporary society.',
                'rows'  => 3,
            ),
            array(
                'key'   => 'field_hero_cta_primary',
                'label' => __('Primary Button Link', 'mlzs'),
                'name'  => 'hero_cta_primary',
                'type'  => 'link',
                'return_format' => 'array',
                'instructions' => __('Button text and URL in one link field.', 'mlzs'),
            ),
            array(
                'key'   => 'field_hero_cta_primary_icon',
                'label' => __('Primary Button Icon', 'mlzs'),
                'name'  => 'hero_cta_primary_icon',
                'type'  => 'text',
                'placeholder' => 'e.g. arrow-up-right',
                'default_value' => 'arrow-up-right',
                'instructions' => __('Lucide icon name (e.g. arrow-up-right, play-circle). Leave blank to hide icon.', 'mlzs'),
            ),
            array(
                'key'   => 'field_hero_cta_secondary',
                'label' => __('Secondary Button Link', 'mlzs'),
                'name'  => 'hero_cta_secondary',
                'type'  => 'link',
                'return_format' => 'array',
                'instructions' => __('Button text and URL in one link field.', 'mlzs'),
            ),
            array(
                'key'   => 'field_hero_cta_secondary_icon',
                'label' => __('Secondary Button Icon', 'mlzs'),
                'name'  => 'hero_cta_secondary_icon',
                'type'  => 'text',
                'placeholder' => 'e.g. play-circle',
                'default_value' => 'play-circle',
                'instructions' => __('Lucide icon name. Leave blank to hide icon.', 'mlzs'),
            ),
            array(
                'key'   => 'field_hero_stats',
                'label' => __('Stats Row', 'mlzs'),
                'name'  => 'hero_stats',
                'type'  => 'repeater',
                'layout' => 'table',
                'button_label' => __('Add Stat', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key'   => 'field_hero_stat_number',
                        'label' => __('Number / Value', 'mlzs'),
                        'name'  => 'stat_number',
                        'type'  => 'text',
                        'placeholder' => 'e.g. 100%',
                    ),
                    array(
                        'key'   => 'field_hero_stat_label',
                        'label' => __('Label', 'mlzs'),
                        'name'  => 'stat_label',
                        'type'  => 'text',
                        'placeholder' => 'e.g. University Acceptance',
                    ),
                ),
            ),
            array(
                'key'   => 'field_tab_welcome',
                'label' => __('Welcome Section', 'mlzs'),
                'name'  => '',
                'type'  => 'tab',
            ),
            array(
                'key'   => 'field_welcome_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name'  => 'welcome_badge',
                'type'  => 'text',
                'default_value' => 'Welcome to Our Campus',
            ),
            array(
                'key'   => 'field_welcome_heading_line1',
                'label' => __('Heading (First Line)', 'mlzs'),
                'name'  => 'welcome_heading_line1',
                'type'  => 'text',
                'default_value' => 'Mount Litera Zee School, Alwar',
            ),
            array(
                'key'   => 'field_welcome_heading_highlight',
                'label' => __('Heading (Highlighted Part)', 'mlzs'),
                'name'  => 'welcome_heading_highlight',
                'type'  => 'text',
                'default_value' => 'A Great School For A Great Future',
            ),
            array(
                'key'   => 'field_welcome_description',
                'label' => __('Description', 'mlzs'),
                'name'  => 'welcome_description',
                'type'  => 'textarea',
                'default_value' => 'Mount Litera Zee School will provide a complete and unique educational experience for the child, preparing the child for a successful life in the contemporary society. MLZS create an excellent educational institution synthesizing the human values with the highest quality of teaching–learning using modern technology-driven tools.',
                'rows'  => 4,
            ),
            array(
                'key'   => 'field_welcome_cta_primary',
                'label' => __('Primary Button Link', 'mlzs'),
                'name'  => 'welcome_cta_primary',
                'type'  => 'link',
                'return_format' => 'array',
                'instructions' => __('Button text and URL in one link field.', 'mlzs'),
            ),
            array(
                'key'   => 'field_welcome_cta_primary_icon',
                'label' => __('Primary Button Icon', 'mlzs'),
                'name'  => 'welcome_cta_primary_icon',
                'type'  => 'text',
                'placeholder' => 'e.g. arrow-right',
                'default_value' => 'arrow-right',
                'instructions' => __('Lucide icon name. Leave blank to hide icon.', 'mlzs'),
            ),
            array(
                'key'   => 'field_welcome_cta_secondary',
                'label' => __('Secondary Button Link', 'mlzs'),
                'name'  => 'welcome_cta_secondary',
                'type'  => 'link',
                'return_format' => 'array',
                'instructions' => __('Button text and URL in one link field.', 'mlzs'),
            ),
            array(
                'key'   => 'field_welcome_cta_secondary_icon',
                'label' => __('Secondary Button Icon', 'mlzs'),
                'name'  => 'welcome_cta_secondary_icon',
                'type'  => 'text',
                'placeholder' => 'e.g. external-link',
                'default_value' => '',
                'instructions' => __('Lucide icon name. Leave blank to hide icon.', 'mlzs'),
            ),
            array(
                'key'   => 'field_welcome_cards',
                'label' => __('Feature Cards', 'mlzs'),
                'name'  => 'welcome_cards',
                'type'  => 'repeater',
                'min'   => 2,
                'max'   => 2,
                'layout' => 'block',
                'button_label' => __('Add Card', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key'   => 'field_welcome_card_icon',
                        'label' => __('Lucide Icon Name', 'mlzs'),
                        'name'  => 'card_icon',
                        'type'  => 'text',
                        'placeholder' => 'e.g. book-open, award',
                        'default_value' => 'book-open',
                    ),
                    array(
                        'key'   => 'field_welcome_card_title',
                        'label' => __('Card Title', 'mlzs'),
                        'name'  => 'card_title',
                        'type'  => 'text',
                        'default_value' => 'The Best Learning Methods',
                    ),
                    array(
                        'key'   => 'field_welcome_card_description',
                        'label' => __('Card Description', 'mlzs'),
                        'name'  => 'card_description',
                        'type'  => 'textarea',
                        'rows'  => 3,
                        'default_value' => 'Mount Litera Zee School will provide a complete and unique educational experience for the child, preparing the child for a successful life in the contemporary society. MLZS create an excellent educational institution synthesizing the human values with the highest quality of teaching–learning using modern technology-driven tools for preparing a well-rounded personality for our society.',
                    ),
                    array(
                        'key'   => 'field_welcome_card_style',
                        'label' => __('Card Style', 'mlzs'),
                        'name'  => 'card_style',
                        'type'  => 'select',
                        'choices' => array(
                            'primary' => __('Primary (purple accent)', 'mlzs'),
                            'accent'  => __('Accent (amber/orange)', 'mlzs'),
                        ),
                        'default_value' => 'primary',
                    ),
                ),
            ),
            array(
                'key'   => 'field_tab_approach',
                'label' => __('Approach Section', 'mlzs'),
                'name'  => '',
                'type'  => 'tab',
            ),
            array(
                'key'   => 'field_approach_badge',
                'label' => __('Badge Text', 'mlzs'),
                'name'  => 'approach_badge',
                'type'  => 'text',
                'default_value' => 'Our Philosophy',
            ),
            array(
                'key'   => 'field_approach_heading',
                'label' => __('Section Heading', 'mlzs'),
                'name'  => 'approach_heading',
                'type'  => 'text',
                'default_value' => 'The Litera Octave Approach',
            ),
            array(
                'key'   => 'field_approach_description',
                'label' => __('Section Description', 'mlzs'),
                'name'  => 'approach_description',
                'type'  => 'textarea',
                'rows'  => 3,
                'default_value' => 'A holistic framework for world-class education, seamlessly integrating eight core pillars of excellence to nurture future leaders.',
            ),
            array(
                'key'   => 'field_approach_pillars',
                'label' => __('Pillars (tabs + slides)', 'mlzs'),
                'name'  => 'approach_pillars',
                'type'  => 'repeater',
                'min'   => 1,
                'layout' => 'block',
                'button_label' => __('Add Pillar', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key'   => 'field_approach_pillar_icon',
                        'label' => __('Lucide Icon', 'mlzs'),
                        'name'  => 'icon',
                        'type'  => 'text',
                        'placeholder' => 'e.g. bar-chart-3',
                        'default_value' => 'bar-chart-3',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_label',
                        'label' => __('Tab Label', 'mlzs'),
                        'name'  => 'label',
                        'type'  => 'text',
                        'placeholder' => 'e.g. Assessment',
                        'default_value' => 'Assessment',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_tag',
                        'label' => __('Tag (uppercase text)', 'mlzs'),
                        'name'  => 'tag',
                        'type'  => 'text',
                        'placeholder' => 'e.g. Litera Assessment',
                        'default_value' => 'Litera Assessment',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_title_line1',
                        'label' => __('Title First Line', 'mlzs'),
                        'name'  => 'title_line1',
                        'type'  => 'text',
                        'default_value' => 'Litera',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_title_highlight',
                        'label' => __('Title Highlighted', 'mlzs'),
                        'name'  => 'title_highlight',
                        'type'  => 'text',
                        'default_value' => 'Assessment',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_description',
                        'label' => __('Description', 'mlzs'),
                        'name'  => 'description',
                        'type'  => 'textarea',
                        'rows'  => 4,
                        'default_value' => 'Our assessments focus on identifying what students are good at instead of whether they are good or not. MLZS assessments take place on a continuous basis and at the child\'s pace rather than through only stressful periodic exams.',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_pills',
                        'label' => __('Pill Tags', 'mlzs'),
                        'name'  => 'pills',
                        'type'  => 'repeater',
                        'layout' => 'table',
                        'button_label' => __('Add Tag', 'mlzs'),
                        'sub_fields' => array(
                            array(
                                'key'   => 'field_approach_pillar_pill_text',
                                'label' => __('Tag Text', 'mlzs'),
                                'name'  => 'pill_text',
                                'type'  => 'text',
                                'placeholder' => 'e.g. Continuous',
                            ),
                        ),
                    ),
                    array(
                        'key'   => 'field_approach_pillar_button',
                        'label' => __('Button Link', 'mlzs'),
                        'name'  => 'button',
                        'type'  => 'link',
                        'return_format' => 'array',
                    ),
                    array(
                        'key'   => 'field_approach_pillar_image',
                        'label' => __('Slide Image', 'mlzs'),
                        'name'  => 'image',
                        'type'  => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                    ),
                ),
            ),
            array(
                'key'   => 'field_tab_academics',
                'label' => __('Academics Section', 'mlzs'),
                'name'  => '',
                'type'  => 'tab',
            ),
            array(
                'key'   => 'field_academics_badge_text',
                'label' => __('Badge Text', 'mlzs'),
                'name'  => 'academics_badge_text',
                'type'  => 'text',
                'default_value' => 'Student Life',
            ),
            array(
                'key'   => 'field_academics_badge_icon',
                'label' => __('Badge Icon', 'mlzs'),
                'name'  => 'academics_badge_icon',
                'type'  => 'text',
                'placeholder' => 'e.g. graduation-cap',
                'default_value' => 'graduation-cap',
            ),
            array(
                'key'   => 'field_academics_heading',
                'label' => __('Section Heading', 'mlzs'),
                'name'  => 'academics_heading',
                'type'  => 'text',
                'default_value' => 'Academics & Beyond',
            ),
            array(
                'key'   => 'field_academics_description',
                'label' => __('Section Description', 'mlzs'),
                'name'  => 'academics_description',
                'type'  => 'textarea',
                'rows'  => 3,
                'default_value' => 'We believe education extends far beyond the classroom walls. Explore the diverse opportunities that shape our students into well-rounded global leaders through arts, sports, and community engagement.',
            ),
            array(
                'key'   => 'field_academics_tabs',
                'label' => __('Tabs & Panels', 'mlzs'),
                'name'  => 'academics_tabs',
                'type'  => 'repeater',
                'min'   => 1,
                'layout' => 'block',
                'button_label' => __('Add Tab / Panel', 'mlzs'),
                'instructions' => __('Each row = one tab button + one panel of cards. Use Tab Slug for JS (e.g. fun, sports, events).', 'mlzs'),
                'sub_fields' => array(
                    array(
                        'key'   => 'field_academics_tab_icon',
                        'label' => __('Tab Icon', 'mlzs'),
                        'name'  => 'tab_icon',
                        'type'  => 'text',
                        'placeholder' => 'e.g. palette, trophy',
                        'default_value' => 'palette',
                    ),
                    array(
                        'key'   => 'field_academics_tab_label',
                        'label' => __('Tab Label', 'mlzs'),
                        'name'  => 'tab_label',
                        'type'  => 'text',
                        'placeholder' => 'e.g. Fun & Art',
                        'default_value' => 'Fun & Art',
                    ),
                    array(
                        'key'   => 'field_academics_tab_slug',
                        'label' => __('Tab Slug', 'mlzs'),
                        'name'  => 'tab_slug',
                        'type'  => 'text',
                        'placeholder' => 'e.g. fun (no spaces)',
                        'default_value' => 'fun',
                        'instructions' => __('Unique ID for this tab/panel (used in HTML).', 'mlzs'),
                    ),
                    array(
                        'key'   => 'field_academics_cards',
                        'label' => __('Cards', 'mlzs'),
                        'name'  => 'cards',
                        'type'  => 'repeater',
                        'min'   => 1,
                        'layout' => 'block',
                        'button_label' => __('Add Card', 'mlzs'),
                        'sub_fields' => array(
                            array(
                                'key'   => 'field_academics_card_image',
                                'label' => __('Card Image', 'mlzs'),
                                'name'  => 'image',
                                'type'  => 'image',
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key'   => 'field_academics_card_tag',
                                'label' => __('Tag', 'mlzs'),
                                'name'  => 'tag',
                                'type'  => 'text',
                                'placeholder' => 'e.g. Clubs',
                            ),
                            array(
                                'key'   => 'field_academics_card_tag_style',
                                'label' => __('Tag Style', 'mlzs'),
                                'name'  => 'tag_style',
                                'type'  => 'select',
                                'choices' => array(
                                    'primary' => __('Primary (purple)', 'mlzs'),
                                    'accent'  => __('Accent (amber)', 'mlzs'),
                                ),
                                'default_value' => 'primary',
                            ),
                            array(
                                'key'   => 'field_academics_card_title',
                                'label' => __('Card Title', 'mlzs'),
                                'name'  => 'title',
                                'type'  => 'text',
                                'default_value' => 'Litera Clubs',
                            ),
                            array(
                                'key'   => 'field_academics_card_description',
                                'label' => __('Description', 'mlzs'),
                                'name'  => 'description',
                                'type'  => 'textarea',
                                'rows'  => 3,
                            ),
                            array(
                                'key'   => 'field_academics_card_link',
                                'label' => __('Link', 'mlzs'),
                                'name'  => 'link',
                                'type'  => 'link',
                                'return_format' => 'array',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key'   => 'field_academics_cta',
                'label' => __('View All Link', 'mlzs'),
                'name'  => 'academics_cta',
                'type'  => 'link',
                'return_format' => 'array',
                'instructions' => __('Bottom CTA e.g. View All Activities.', 'mlzs'),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'home.php',
                ),
            ),
        ),
    ));
}
add_action('acf/init', 'mlzs_acf_hero_field_group');